#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "installing vncuseradd to /usr/local/bin..."
sudo install -Dm0755 "${SCRIPT_DIR}/vncuseradd" /usr/local/bin/vncuseradd

echo "installing man page..."
sudo install -Dm0644 "${SCRIPT_DIR}/vncuseradd.8.gz" /usr/local/man/man8/vncuseradd.8.gz

echo "updating man database..."
sudo mandb >/dev/null 2>&1

echo "done!"
