#!/usr/bin/env bash
SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "moving vncuseradd to /usr/local/bin..."
sudo cp ${SCRIPT_DIR}/vncuseradd /usr/local/bin/vncuseradd

echo "moving man page..."
sudo mkdir -p /usr/local/man/man8
sudo cp ${SCRIPT_DIR}/vncuseradd.8.gz /usr/local/man/man8

echo "updating man database..."
sudo mandb

echo "done!"